# Generated by Django 3.1.7 on 2021-05-25 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=120, unique=True)),
                ('daily_wages', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist', models.CharField(max_length=200, unique=True)),
                ('state', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Transgender', 'Transgender'), ('Non-binary', 'Non-binary'), ('intersex', 'intersex'), ('I prefer not to say', 'I prefer not to say')], max_length=50, null=True)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=120)),
                ('address', models.CharField(max_length=300)),
                ('adhar_card', models.CharField(max_length=120)),
                ('driving_licence', models.CharField(max_length=120, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('join_date', models.DateField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('current_status', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=20, null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.job')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.location')),
            ],
        ),
        migrations.CreateModel(
            name='HireWorkers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('customer', models.CharField(max_length=120)),
                ('hire', models.CharField(choices=[('Hire Worker', 'Hire Worker'), ('Cancel worker', 'Cancel worker')], max_length=20, null=True)),
                ('hire_date', models.DateField(auto_now=True)),
                ('days', models.IntegerField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.location')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Bad', 'Bad')], max_length=20, null=True)),
                ('content', models.TextField(null=True)),
                ('date', models.DateField(auto_now=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worker_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workers.worker')),
            ],
        ),
    ]
