# Generated by Django 3.1.7 on 2021-05-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hireworkers',
            name='customer_phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
