# Generated by Django 3.1.7 on 2021-06-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20210527_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
